/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazUsuario;

import control.Control;
import excepciones.FachadaException;
import objetosNegocio.*;
import objetosServicio.Fecha;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author User
 */
public class VentanaPrincipalEmpleado extends javax.swing.JFrame {
    //Variables de Estado
    private Control control;
    private Usuario usuarioLogueado;
    private String horaEntradaRegistrada;
    private String fechaActual;
    private Timer timer;
    private String codigoEmpleadoLogueado;
    
    private Asistencia asistenciaPendiente;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipalEmpleado.class.getName());

    /**
     * Creates new form VentanaPrincipalEmpleado
     */
    public VentanaPrincipalEmpleado(Control control) {
        this(control, null);
    }

    public VentanaPrincipalEmpleado(Control control, Usuario usuario) {
        this.control = control;
        this.usuarioLogueado = usuario;
        
        // Obtener código de empleado a partir del usuario logueado
         if (usuarioLogueado != null) {
            try {
                codigoEmpleadoLogueado = control.obtenerCodigoEmpleadoPorUsuario(usuarioLogueado.getUsuario());
                if (codigoEmpleadoLogueado == null) {
                    codigoEmpleadoLogueado = solicitarCodigoEmpleado();
                }
            } catch (FachadaException ex) {
                JOptionPane.showMessageDialog(this,
                        "Error al obtener código de empleado: " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
                codigoEmpleadoLogueado = solicitarCodigoEmpleado();
            }
        } else {
            codigoEmpleadoLogueado = solicitarCodigoEmpleado();
        }
        
        
        initComponents();
        setLocationRelativeTo(null);
    
        
        // Hacer no editables los campos de hora (solo para mostrar)
        jFormattedTextField1.setEditable(false);
        jFormattedTextField2.setEditable(false);
        verificarSesionActiva();

        iniciarReloj(); //Reloj en tiempo real
    }
        // ========== SOLICITAR CÓDIGO DE EMPLEADO MANUALMENTE ==========
    private String solicitarCodigoEmpleado() {
        String codigo = JOptionPane.showInputDialog(this,
            "No se encontró un empleado asociado a su usuario.\n" +
            "Ingrese su código de empleado manualmente:",
            "Código de Empleado", JOptionPane.QUESTION_MESSAGE);
        
        if (codigo != null && !codigo.trim().isEmpty()) {
            return codigo.trim();
        } else {
            // Si cancela o no ingresa, mostrar advertencia y permitir continuar (pero no podrá registrar)
            JOptionPane.showMessageDialog(this,
                "No se ha ingresado un código de empleado. Podrá registrarlo después.",
                "Advertencia", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        
    }
     // ========== NUEVO: VERIFICAR SESIÓN ACTIVA ==========
     private void verificarSesionActiva() {
        if (codigoEmpleadoLogueado == null) {
            jButton1.setEnabled(false);
            jButton3.setEnabled(false);
            return;
        }

        try {
            // Buscar asistencia pendiente del día actual
            asistenciaPendiente = control.obtenerAsistenciaPendiente(codigoEmpleadoLogueado);
            if (asistenciaPendiente != null) {
                // Mostrar la hora de entrada
                jFormattedTextField1.setText(asistenciaPendiente.getHoraIngreso());
                jLabel7.setText(asistenciaPendiente.getFecha().toString());
                horaEntradaRegistrada = asistenciaPendiente.getHoraIngreso();

                // Configurar botones
                jButton1.setEnabled(false);
                jButton3.setEnabled(true);

                JOptionPane.showMessageDialog(this,
                        "Sesión activa encontrada.\nEntrada: " + horaEntradaRegistrada,
                        "Sesión Activa", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // No hay sesión activa
                jButton1.setEnabled(true);
                jButton3.setEnabled(false);
            }
        } catch (FachadaException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al verificar sesión: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REGISTRO DE ASISTENCIA");

        jButton1.setText("Registrar Entrada");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Salir");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jFormattedTextField1.addActionListener(this::jFormattedTextField1ActionPerformed);

        jLabel2.setText("Hora Entrada");

        jLabel3.setText("Hora Salida");

        jFormattedTextField2.addActionListener(this::jFormattedTextField2ActionPerformed);

        jLabel4.setText("Hora Actual");

        jLabel5.setText("Fecha");

        jButton3.setText("Registrar Salida");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel6.setText("--:--:--");

        jLabel7.setText("dd/MM/yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addGap(0, 78, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ================== MÉTODO PARA EL RELOJ EN TIEMPO REAL ==================
    private void iniciarReloj() {
        // Actualizar fecha actual
        SimpleDateFormat sdfFecha = new SimpleDateFormat("dd/MM/yyyy");
        fechaActual = sdfFecha.format(new Date());
        jLabel7.setText(fechaActual);

        // Crear timer que actualiza la hora cada segundo
        timer = new Timer(1000, e -> {
            SimpleDateFormat sdfHora = new SimpleDateFormat("HH:mm:ss");
            jLabel6.setText(sdfHora.format(new Date()));
        });
        timer.start();
    }
    // ================== ACCIÓN: REGISTRAR ENTRADA ==================
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (codigoEmpleadoLogueado == null) {
            JOptionPane.showMessageDialog(this, 
                "No se tiene un código de empleado asociado. Contacte al administrador.",
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verificar que no haya una pendiente (por si acaso)
        try {
            Asistencia pendiente = control.obtenerAsistenciaPendiente(codigoEmpleadoLogueado);
            if (pendiente != null) {
                JOptionPane.showMessageDialog(this,
                        "Ya tiene una sesión activa. Registre la salida primero.",
                        "Sesión Activa", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (FachadaException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        SimpleDateFormat sdfHora = new SimpleDateFormat("HH:mm");
        String horaActual = sdfHora.format(new Date());
        jFormattedTextField1.setText(horaActual);
        horaEntradaRegistrada = horaActual;

        SimpleDateFormat sdfFecha = new SimpleDateFormat("dd/MM/yyyy");
        fechaActual = sdfFecha.format(new Date());
        jLabel7.setText(fechaActual);

        // Crear asistencia con estado PENDIENTE
        java.util.Calendar cal = java.util.Calendar.getInstance();
        Fecha fecha = new Fecha(
                cal.get(java.util.Calendar.DAY_OF_MONTH),
                cal.get(java.util.Calendar.MONTH) + 1,
                cal.get(java.util.Calendar.YEAR)
        );
        Asistencia asistencia = new Asistencia(codigoEmpleadoLogueado, fecha, horaActual);
        asistencia.setEstado("PENDIENTE");
        asistencia.setHoraSalida("");

        try {
            // Guardar la asistencia con estado PENDIENTE
            control.registrarAsistencia(asistencia); // Necesita un método que acepte Asistencia
            asistenciaPendiente = asistencia;
            jButton1.setEnabled(false);
            jButton3.setEnabled(true);
            JOptionPane.showMessageDialog(this,
                    "Entrada registrada a las " + horaActual + "\nFecha: " + fechaActual,
                    "Registro de Entrada", JOptionPane.INFORMATION_MESSAGE);
        } catch (FachadaException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error al registrar entrada: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if (horaEntradaRegistrada == null || asistenciaPendiente == null) {
            JOptionPane.showMessageDialog(this,
                    "No hay sesión activa. Registre la entrada primero.",
                    "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Seguro que desea registrar la salida?",
                "Confirmar Salida",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            SimpleDateFormat sdfHora = new SimpleDateFormat("HH:mm");
            String horaSalida = sdfHora.format(new Date());
            jFormattedTextField2.setText(horaSalida);

            // Actualizar la asistencia pendiente
            asistenciaPendiente.setHoraSalida(horaSalida);
            asistenciaPendiente.setEstado("PRESENTE");

            try {
                // Actualizar el registro en el archivo
                control.actualizarAsistencia(asistenciaPendiente);

                // Limpiar campos
                jFormattedTextField1.setText("");
                jFormattedTextField2.setText("");
                horaEntradaRegistrada = null;
                asistenciaPendiente = null;
                jButton1.setEnabled(true);
                jButton3.setEnabled(false);

                JOptionPane.showMessageDialog(this,
                        "Salida registrada correctamente.",
                        "Registro de Salida", JOptionPane.INFORMATION_MESSAGE);
            } catch (FachadaException ex) {
                JOptionPane.showMessageDialog(this,
                        "Error al registrar salida: " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Detener el timer antes de cerrar
         if (timer != null) timer.stop();
        dispose();  // Cierra la ventana
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Control control = new Control();           // ← Se crea el control aquí
            new VentanaPrincipalEmpleado(control).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
